<a href="https://colab.research.google.com/github/HoPhuocMinhQuan20104052/HoPhuocMinhQuan/blob/main/Week_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x = [[0,0],[1,0],[0,1],[1,1]]
y = [0,1,1,1]
model = Perceptron()
model.fit(x,y)
print('Do chinh xac',model.score(x,y))
x_test =[[0.5,0],[0.9,-0.2],[1,-0.5],[0.2,0.7]]
y_test = model.predict(x_test)
print(y_test)

Do chinh xac 1.0
[0 1 0 1]


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x = [[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
y = [1,1,0,0]
model = Perceptron()
model.fit(x,y)
print('Do chinh xac',model.score(x,y))
x_test =[[0,0],[1,0],[0,1],[1,1]]
y_test = model.predict(x_test)
print(y_test)

Do chinh xac 1.0
[0 0 0 0]


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd
url='/content/data_crab.csv'
data= pd.read_csv(url)
data = data[:100]
x=data.drop(['sp','sex'],axis=True)   
y=data['sex'].replace(['M','F'],['1','0'])
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
model=Perceptron()
model.fit(x_train,y_train)
print('độ chính xác',model.score(x,y))
x_test = [[10,10.8,11,19,23,7],[9,15,12.6,38.1,42,15.1],[15,21.3,16.7,38.6,44.5,17],[40,17.5,13.2,31.7,47.9,12]] 
y_test = model.predict(x_test)
print(y_test)

độ chính xác 0.89
['0' '1' '0' '0']


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd
url='/content/iris.csv'
data= pd.read_csv(url)
data = data[:150]
x=data.drop(['variety'],axis = True)
y=data['variety'].replace(['Setosa','Versicolor','Virginica'],[1,0,0])
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
model=Perceptron()
model.fit(x_train,y_train)
print('độ chính xác',model.score(x,y))
x_test = [[6.9,3.2,5.2,2],[6.7,3.1,5.6,2.4],[6.5,3.7,1.5,2.3]]
y_test = model.predict(x_test)
print(y_test)



độ chính xác 1.0
[0 0 1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"
